name: coolmovies
description: A new Flutter project.

publish_to: "none"

version: 1.0.8

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.0.0

  cupertino_icons: ^1.0.2
  either_dart: ^0.2.0
  equatable: ^2.0.3
  flutter_secure_storage: ^5.0.2
  responsive_framework: ^0.2.0
  intl: ^0.17.0
  google_fonts: ^3.0.1
  faker: ^2.0.0
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  mocktail: ^0.3.0
  remove_from_coverage: ^2.0.0
  integration_test:
    sdk: flutter
  mocktail_image_network: ^0.3.1
  mockingjay: ^0.3.0

flutter:
  uses-material-design: true
