name: Code static analysis

runs:
  using: "composite"
  steps:
    - uses: subosito/flutter-action@v1
    - name: Analyze commands
      shell: bash
      run: |
        cd ./coolmovies_mobile
        flutter pub get
        flutter format --set-exit-if-changed .
        flutter analyze .
        ./scripts/runCodeMetrics.sh

    - name: upload metrics html
      uses: actions/upload-artifact@v3
      with:
        name: complexity-metrics
        path: |
          **/metrics
