name: Code static analysis

runs:
  using: "composite"
  steps:
    # - name: Get token
    #   uses: peter-murray/workflow-application-token-action@v1
    #   id: get-token
    #   with:
    #     application_id: ${{ secrets.APPLICATION_ID }}
    #     application_id: ${{ secrets.APP_PRIVATE_KEY }}

    - uses: actions/checkout@v2
      with:
        token: ${{secrets.GITHUB_TOKEN}}

    - uses: subosito/flutter-action@v1
    - name: Analyze commands
      run: |
        cd ./coolmovies_mobile
        flutter pub get
        flutter format --set-exit-if-changed .
        flutter analyze .
        ./scripts/runCodeMetrics.sh

    - name: upload metrics html
      uses: actions/upload-artifact@v3
        with:
          name: complexity-metrics
          path: |
            **/metrics
