name: build artifact

on:
  push:
    tags:
      - v*

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: |
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Generate test results
        run: |
          ./scripts/runTests.sh
          ./scripts/runCodeMetrics.sh
          flutter test --coverage
          flutter test --machine > test-results.json

      - name: upload metrics html files
        uses: actions/upload-artifact@v3
        with:
          name: html-metrics
          path: |
            **/coverage
            **/metrics

      - uses: dorny/test-reporter@v1.4.2
        with:
          name: test-results
          path: coolmovies_mobile/test-results.json
          reporter: flutter-json

      - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: coolmovies_mobile/coverage/lcov.info
          min_coverage: 0

  build-apk:
    runs-on: ubuntu-latest
    name: Build .apk step
    needs:
      - analyze
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
      - run: |
          flutter pub get
          flutter clean
          flutter build apk --release
      - name: Upload appbundle
        uses: actions/upload-artifact@v2.1.4
        with:
          name: coolmovies
          path: build/app/outputs/bundle/release/app-release.apk
