name: Flutter CI

on:
  push:
    branches:
      - master

env:
  flutter_version: "3.0.5"
  java_version: "12.x"

jobs:
  analyze:
    runs-on: macos-12
    defaults:
      run:
        working-directory: ./coolmovies_mobile

    steps:
      - name: flutter setup
        uses: regisksc/coolmovies_challenge/.github/actions/setup/action.yml@main
        with:
          - flutter-version: ${{ envs.flutter-version }}
          - flutter-version: ${{ envs.java-version }}

      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
