name: Flutter CI

on: [push]

env:
  flutter-version: "3.0.5"
  java-version: "12.x"

jobs:
  analyze:
    runs-on: macos-12
    defaults:
      run:
        working-directory: ./coolmovies_mobile

    steps:
      - name: flutter setup
        uses: regisksc/coolmovies_challenge/.github/actions/setup/action.yml@main
        with:
          flutter-version: ${{ env.flutter-version }}
          java-version: ${{ env.java-version }}

      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
