name: Flutter CI

on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/analyze@main

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/test@main
