name: Flutter CI

on: [push]

env:
  flutter-version: "3.0.5"
  java-version: "12.x"

jobs:
  setup:
    runs-on: macos-12
    uses: ./.github/actions/setup/action.yml
      with:
        flutter-version: ${{ env.flutter-version }}
        java-version: ${{ env.java-version }}
        
  analyze:
    runs-on: macos-12
    defaults:
      run:
        working-directory: ./coolmovies_mobile

    steps:
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
