name: Flutter CI

on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coolmovies_mobile
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Analyze commands
        run: |
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze .

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coolmovies_mobile
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1

      - name: Generate test results
        run: |
          ./scripts/runTests.sh
          ./scripts/runCodeMetrics.sh
          flutter test --coverage
          flutter test --machine > test-results.json

      - name: upload metrics html files
        uses: actions/upload-artifact@v3
        with:
          name: html-metrics
          path: |
            **/coverage
            **/metrics

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@49af65b0586c274a625a41a2dc8aaaae7d00568b
        with:
          coverage-files: coverage/lcov.*.info
          minimum-coverage: 0
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
